### ISSUE TITLE
Continuous mode

### ISSUE THREAD

**Issue by musaulker** [KarolineH/cam_interface#3]
Hello,

While I was researching for an issue I come across to your project.

I am trying to have a live connection on camera and want to trigger capture picture from computer anytime. 

For first capture, if I connect my camera to the laptop and open it, I can get the photo using gphoto2 or python-gphoto2 library. But after 30-40 seconds maybe camera connection is closed/put into sleep, or due to some other reason I cannot access the camera, so I close and re-open the camera.

I am trying to get overcome this problem. Any suggestions?

**Comment by KarolineH** [comment]
Hi @musaulker,

sounds like your camera is powering down or entering sleep mode. The camera I'm using with gphoto2 has a config called /main/settings/autopoweroff, which I can set to different time-spans or turn off entirely. Check if your camera supports the same, otherwise you might be able to deactivate the automatic sleep mode in the camera menu itself.  This might hidden somewhere in the 'power saving' or 'battery' settings. Hope that helps.
